// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3bvYjO5WHJOl5Y6ALYfcgVafiILKfFk4',
    appId: '1:906684975692:web:236cf280f615d8ac9642e9',
    messagingSenderId: '906684975692',
    projectId: 'login-app-d5e84',
    authDomain: 'login-app-d5e84.firebaseapp.com',
    storageBucket: 'login-app-d5e84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzV7Kj7kwv42a3G6AzfYGMnwacwzfkAn0',
    appId: '1:906684975692:android:82e7ffc2b8a03d279642e9',
    messagingSenderId: '906684975692',
    projectId: 'login-app-d5e84',
    storageBucket: 'login-app-d5e84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPWuMJbov_4vKEDVuDIsF_Rx3BATVDchs',
    appId: '1:906684975692:ios:762e67284924d1e79642e9',
    messagingSenderId: '906684975692',
    projectId: 'login-app-d5e84',
    storageBucket: 'login-app-d5e84.appspot.com',
    iosBundleId: 'com.example.signIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPWuMJbov_4vKEDVuDIsF_Rx3BATVDchs',
    appId: '1:906684975692:ios:f31b9a3d2fcd710d9642e9',
    messagingSenderId: '906684975692',
    projectId: 'login-app-d5e84',
    storageBucket: 'login-app-d5e84.appspot.com',
    iosBundleId: 'com.example.signIn.RunnerTests',
  );
}
